#!/bin/sh
#
# @name Vertical Technologies DeltaQuad
#
# @type Standard VTOL
# @class VTOL
#
# @maintainer Sander Smeets <sander@droneslab.com>
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output MAIN5 Right elevon
# @output MAIN6 Left elevon
# @output MAIN7 Pusher motor
# @output MAIN8 Pusher reverse channel
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.vtol_defaults



param set-default ASPD_PRIMARY -1
param set-default BAT1_A_PER_V 64.0
param set-default BAT1_CAPACITY 23000.0
param set-default BAT1_I_CHANNEL 17
param set-default BAT1_N_CELLS 4
param set-default BAT1_R_INTERNAL 0.004
param set-default BAT1_V_CHANNEL 16
param set-default BAT1_V_DIV 19.0

param set-default BAT_A_PER_V 64.0
param set-default BAT_CAPACITY 23000.0
param set-default BAT_N_CELLS 4
param set-default BAT_R_INTERNAL 0.004
param set-default BAT_V_DIV 19.0

param set-default BAT_ADC_CHANNEL 16
param set-default BAT_CRIT_THR 0.05
param set-default BAT_EMERGEN_THR 0.07
param set-default BAT_LOW_THR 0.10
param set-default CAM_CAP_FBACK 0
param set-default CBRK_AIRSPD_CHK 162128
param set-default CBRK_IO_SAFETY 22027
param set-default COM_ARM_IMU_ACC 1.00
param set-default COM_ARM_SDCARD 2
param set-default COM_LOW_BAT_ACT 3
param set-default COM_POSCTL_NAVL 1
param set-default COM_POS_FS_DELAY 30
param set-default COM_POS_FS_EPH 20.0
param set-default COM_POS_FS_EPV 30.0
param set-default COM_POS_FS_GAIN 0
param set-default COM_PREARM_MODE 0
param set-default COM_RC_IN_MODE 1
param set-default COM_RC_LOSS_T 10.0
param set-default COM_RC_OVERRIDE 0
param set-default EKF2_ACC_B_NOISE 0.006
param set-default EKF2_ARSP_THR 10.0
param set-default EKF2_FUSE_BETA 1
param set-default EKF2_GPS_POS_X -0.12
param set-default EKF2_GPS_P_GATE 10.0
param set-default EKF2_GPS_V_GATE 10.0
param set-default EKF2_IMU_POS_X -0.12
param set-default EKF2_MULTI_IMU 3
param set-default EKF2_MULTI_MAG 2
param set-default EKF2_REQ_EPH 5.0
param set-default EKF2_REQ_EPV 10.0
param set-default EKF2_REQ_HDRIFT 0.5
param set-default EKF2_REQ_SACC 1.0
param set-default EKF2_TAU_VEL 0.5
param set-default FW_ARSP_MODE 1
param set-default FW_BAT_SCALE_EN 1
param set-default FW_L1_PERIOD 25.0
param set-default FW_MAN_P_MAX 30.0
param set-default FW_PR_FF 0.7
param set-default FW_PR_I 0.4
param set-default FW_PR_P 0.3
param set-default FW_PSP_OFF 7.0
param set-default FW_P_LIM_MAX 15.0
param set-default FW_P_LIM_MIN -25.0
param set-default FW_P_RMAX_NEG 40.0
param set-default FW_P_RMAX_POS 20.0
param set-default FW_P_TC 0.6
param set-default FW_RR_FF 0.7
param set-default FW_RR_I 0.08
param set-default FW_RR_P 0.18
param set-default FW_R_LIM 35.0
param set-default FW_R_RMAX 40.0
param set-default FW_THR_ALT_SCL 1.15
param set-default FW_THR_CRUISE 0.52
param set-default FW_THR_MAX 0.9
param set-default FW_THR_MIN 0.3
param set-default FW_THR_SLEW_MAX 2.0
param set-default FW_T_CLMB_MAX 2.0
param set-default FW_T_HRATE_FF 0.5
param set-default FW_T_PTCH_DAMP 0.1
param set-default FW_T_RLL2THR 18.0
param set-default FW_T_SEB_R_FF 2.0
param set-default FW_T_SINK_MAX 3.0
param set-default FW_T_SINK_MIN 1.0
param set-default FW_T_SPDWEIGHT 2.0
param set-default FW_T_STE_R_TC 0.001
param set-default FW_T_THR_DAMP 1.0
param set-default FW_T_VERT_ACC 6.0
param set-default FW_T_ALT_TC 8.0
param set-default FW_T_I_GAIN_PIT 0.3
param set-default FW_T_TAS_TC 4.0
param set-default GF_ACTION 2
param set-default IMU_DGYRO_CUTOFF 30.0
param set-default IMU_GYRO_RATEMAX 250
param set-default LNDMC_ALT_MAX 9999.0
param set-default LNDMC_XY_VEL_MAX 1.0
param set-default LNDMC_Z_VEL_MAX 0.6
param set-default MAV_0_CONFIG 101
param set-default MAV_0_FORWARD 1
param set-default MAV_0_MODE 0
param set-default MAV_0_RADIO_CTL 1
param set-default MAV_0_RATE 1200
param set-default MAV_1_CONFIG 102
param set-default MAV_1_FORWARD 1
param set-default MAV_1_MODE 0
param set-default MAV_1_RADIO_CTL 1
param set-default MAV_1_RATE 4000
param set-default MAV_2_CONFIG 103
param set-default MAV_HB_FORW_EN 0
param set-default MAV_TYPE 22
param set-default MC_AIRMODE 1
param set-default MC_PITCHRATE_I 0.15
param set-default MC_PITCHRATE_MAX 120.0
param set-default MC_PITCHRATE_P 0.14
param set-default MC_ROLLRATE_I 0.15
param set-default MC_ROLLRATE_MAX 120.0
param set-default MC_ROLLRATE_P 0.14
param set-default MC_YAWRATE_I 0.40
param set-default MC_YAWRATE_MAX 30.0
param set-default MC_YAWRATE_P 0.35
param set-default MC_YAW_P 4.0
param set-default MIS_DIST_1WP 1000.0
param set-default MIS_DIST_WPS 100000.0
param set-default MIS_TAKEOFF_ALT 15.0
param set-default MIS_YAW_TMT 10.0
param set-default MNT_MODE_IN 3
param set-default MPC_ACC_HOR_MAX 2.0
param set-default MPC_HOLD_MAX_XY 0.5
param set-default MPC_HOLD_MAX_Z 0.5
param set-default MPC_JERK_AUTO 4.0
param set-default MPC_LAND_ALT1 8.0
param set-default MPC_LAND_ALT2 3.0
param set-default MPC_LAND_SPEED 0.6
param set-default MPC_MANTHR_MIN 0.0
param set-default MPC_MAN_TILT_MAX 30.0
param set-default MPC_THR_MAX 0.9
param set-default MPC_THR_MIN 0.1
param set-default MPC_TILTMAX_AIR 25.0
param set-default MPC_TILTMAX_LND 25.0
param set-default MPC_TKO_RAMP_T 1.0
param set-default MPC_TKO_SPEED 1.0
param set-default MPC_VEL_MANUAL 3.0
param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_MAX 5.0
param set-default MPC_XY_VEL_P_ACC 2.0
param set-default MPC_YAWRAUTO_MAX 20.0
param set-default MPC_Z_VEL_MAX_DN 1.5
param set-default MPC_Z_VEL_MAX_UP 1.5
param set-default NAV_DLL_ACT 2
param set-default NAV_FORCE_VT 1
param set-default NAV_GPSF_LT 30.0
param set-default NAV_GPSF_P 10.0
param set-default NAV_GPSF_R 15.0
param set-default NAV_GPSF_TR 0.6
param set-default NAV_LOITER_RAD 100.0
param set-default NAV_RCL_ACT 0
param set-default PWM_MAIN_DIS5 1500
param set-default PWM_MAIN_DIS6 1500
param set-default PWM_MAIN_DIS7 900
param set-default PWM_MAIN_DIS8 1050
param set-default PWM_MAIN_DIS9 1100
param set-default PWM_MAIN_DISARM 900
param set-default PWM_MAIN_MAX 2000

param set-default RC_CHAN_CNT 18
param set-default RC_MAP_MODE_SW 6
param set-default RC_MAP_PITCH 3
param set-default RC_MAP_POSCTL_SW 8
param set-default RC_MAP_RETURN_SW 5
param set-default RC_MAP_ROLL 2
param set-default RC_MAP_THROTTLE 1
param set-default RC_MAP_TRANS_SW 7
param set-default RC_MAP_YAW 4

param set-default RTL_CONE_ANG 65
param set-default RTL_DESCEND_ALT 40.0
param set-default RTL_FLT_TIME 110.0
param set-default RTL_LAND_DELAY 0.0
param set-default RTL_LOITER_RAD 50.0
param set-default RTL_MIN_DIST 10.0
param set-default RTL_PLD_MD 0
param set-default RTL_RETURN_ALT 60.0
param set-default RTL_TYPE 1
param set-default SENS_BOARD_ROT 18
param set-default SENS_EN_THERMAL 1
param set-default SENS_IMU_MODE 0
param set-default SENS_MAG_MODE 0
param set-default SER_TEL1_BAUD 57600
param set-default SER_TEL2_BAUD 57600
param set-default TRIG_ACT_TIME 40.0
param set-default TRIG_DISTANCE 22.0
param set-default TRIG_INTERFACE 2
param set-default TRIG_INTERVAL 1000.0
param set-default TRIG_MIN_INTERVA 1.0
param set-default TRIG_MODE 4
param set-default UAVCAN_ENABLE 2
param set-default VT_ARSP_BLEND 8.0
param set-default VT_ARSP_TRANS 15.0
param set-default VT_B_DEC_FF 0.12
param set-default VT_B_DEC_I 0.1
param set-default VT_B_DEC_MSS 1.85
param set-default VT_B_REV_DEL 1.0
param set-default VT_B_REV_OUT 0.5
param set-default VT_B_TRANS_DUR 8.0
param set-default VT_B_TRANS_RAMP 3.0
param set-default VT_B_TRANS_THR 0.7
param set-default VT_DWN_PITCH_MAX 4.0
param set-default VT_ELEV_MC_LOCK 0
param set-default VT_FWD_THRUST_EN 6
param set-default VT_FWD_THRUST_SC 2.0
param set-default VT_FW_ALT_ERR 20.0
param set-default VT_FW_DIFTHR_EN 0
param set-default VT_FW_DIFTHR_SC 0.1
param set-default VT_FW_MIN_ALT 0.0
param set-default VT_FW_MOT_OFFID 1234
param set-default VT_FW_PERM_STAB 1
param set-default VT_FW_QC_P 100
param set-default VT_FW_QC_R 100
param set-default VT_F_TRANS_DUR 8.0
param set-default VT_F_TRANS_THR 1.0
param set-default VT_F_TR_OL_TM 10.0
param set-default VT_IDLE_PWM_MC 1025
param set-default VT_MC_ON_FMU 0
param set-default VT_MOT_ID 1234
param set-default VT_PSHER_RMP_DT 3.0
param set-default VT_TRANS_MIN_TM 8.0
param set-default VT_TRANS_TM_SCL 4.0
param set-default VT_TRANS_TIMEOUT 60.0
param set-default VT_TYPE 2
param set-default WV_EN 1
param set-default WV_GAIN 1.0
param set-default WV_ROLL_MIN 1.0
param set-default WV_YRATE_MAX 90.0 9

set MAV_TYPE 22

set MIXER deltaquad
set MIXER_AUX pass

set PWM_OUT 1234
set PWM_AUX_OUT 12345
